// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: cmd/sidecar/src/proto/drtest.proto

package sidecar

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Object        string                 `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataRequest) Reset() {
	*x = DataRequest{}
	mi := &file_cmd_sidecar_src_proto_drtest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRequest) ProtoMessage() {}

func (x *DataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_sidecar_src_proto_drtest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRequest.ProtoReflect.Descriptor instead.
func (*DataRequest) Descriptor() ([]byte, []int) {
	return file_cmd_sidecar_src_proto_drtest_proto_rawDescGZIP(), []int{0}
}

func (x *DataRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *DataRequest) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

type DataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Checksum      string                 `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
	ObjectPath    string                 `protobuf:"bytes,3,opt,name=object_path,json=objectPath,proto3" json:"object_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataResponse) Reset() {
	*x = DataResponse{}
	mi := &file_cmd_sidecar_src_proto_drtest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataResponse) ProtoMessage() {}

func (x *DataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_sidecar_src_proto_drtest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataResponse.ProtoReflect.Descriptor instead.
func (*DataResponse) Descriptor() ([]byte, []int) {
	return file_cmd_sidecar_src_proto_drtest_proto_rawDescGZIP(), []int{1}
}

func (x *DataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DataResponse) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *DataResponse) GetObjectPath() string {
	if x != nil {
		return x.ObjectPath
	}
	return ""
}

var File_cmd_sidecar_src_proto_drtest_proto protoreflect.FileDescriptor

const file_cmd_sidecar_src_proto_drtest_proto_rawDesc = "" +
	"\n" +
	"\"cmd/sidecar/src/proto/drtest.proto\x12\x06drtest\"Q\n" +
	"\vDataRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x16\n" +
	"\x06object\x18\x03 \x01(\tR\x06object\"e\n" +
	"\fDataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1a\n" +
	"\bchecksum\x18\x02 \x01(\tR\bchecksum\x12\x1f\n" +
	"\vobject_path\x18\x03 \x01(\tR\n" +
	"objectPath2J\n" +
	"\rDataValidator\x129\n" +
	"\fValidateData\x12\x13.drtest.DataRequest\x1a\x14.drtest.DataResponseB\vZ\tsidecar/;b\x06proto3"

var (
	file_cmd_sidecar_src_proto_drtest_proto_rawDescOnce sync.Once
	file_cmd_sidecar_src_proto_drtest_proto_rawDescData []byte
)

func file_cmd_sidecar_src_proto_drtest_proto_rawDescGZIP() []byte {
	file_cmd_sidecar_src_proto_drtest_proto_rawDescOnce.Do(func() {
		file_cmd_sidecar_src_proto_drtest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_sidecar_src_proto_drtest_proto_rawDesc), len(file_cmd_sidecar_src_proto_drtest_proto_rawDesc)))
	})
	return file_cmd_sidecar_src_proto_drtest_proto_rawDescData
}

var file_cmd_sidecar_src_proto_drtest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cmd_sidecar_src_proto_drtest_proto_goTypes = []any{
	(*DataRequest)(nil),  // 0: drtest.DataRequest
	(*DataResponse)(nil), // 1: drtest.DataResponse
}
var file_cmd_sidecar_src_proto_drtest_proto_depIdxs = []int32{
	0, // 0: drtest.DataValidator.ValidateData:input_type -> drtest.DataRequest
	1, // 1: drtest.DataValidator.ValidateData:output_type -> drtest.DataResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmd_sidecar_src_proto_drtest_proto_init() }
func file_cmd_sidecar_src_proto_drtest_proto_init() {
	if File_cmd_sidecar_src_proto_drtest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_sidecar_src_proto_drtest_proto_rawDesc), len(file_cmd_sidecar_src_proto_drtest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_sidecar_src_proto_drtest_proto_goTypes,
		DependencyIndexes: file_cmd_sidecar_src_proto_drtest_proto_depIdxs,
		MessageInfos:      file_cmd_sidecar_src_proto_drtest_proto_msgTypes,
	}.Build()
	File_cmd_sidecar_src_proto_drtest_proto = out.File
	file_cmd_sidecar_src_proto_drtest_proto_goTypes = nil
	file_cmd_sidecar_src_proto_drtest_proto_depIdxs = nil
}
