// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: cmd/sidecar/src/proto/drtest.proto

package sidecar

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataValidator_ValidateData_FullMethodName = "/drtest.DataValidator/ValidateData"
)

// DataValidatorClient is the client API for DataValidator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataValidatorClient interface {
	ValidateData(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataResponse, error)
}

type dataValidatorClient struct {
	cc grpc.ClientConnInterface
}

func NewDataValidatorClient(cc grpc.ClientConnInterface) DataValidatorClient {
	return &dataValidatorClient{cc}
}

func (c *dataValidatorClient) ValidateData(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, DataValidator_ValidateData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataValidatorServer is the server API for DataValidator service.
// All implementations must embed UnimplementedDataValidatorServer
// for forward compatibility.
type DataValidatorServer interface {
	ValidateData(context.Context, *DataRequest) (*DataResponse, error)
	mustEmbedUnimplementedDataValidatorServer()
}

// UnimplementedDataValidatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataValidatorServer struct{}

func (UnimplementedDataValidatorServer) ValidateData(context.Context, *DataRequest) (*DataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateData not implemented")
}
func (UnimplementedDataValidatorServer) mustEmbedUnimplementedDataValidatorServer() {}
func (UnimplementedDataValidatorServer) testEmbeddedByValue()                       {}

// UnsafeDataValidatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataValidatorServer will
// result in compilation errors.
type UnsafeDataValidatorServer interface {
	mustEmbedUnimplementedDataValidatorServer()
}

func RegisterDataValidatorServer(s grpc.ServiceRegistrar, srv DataValidatorServer) {
	// If the following call pancis, it indicates UnimplementedDataValidatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataValidator_ServiceDesc, srv)
}

func _DataValidator_ValidateData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataValidatorServer).ValidateData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataValidator_ValidateData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataValidatorServer).ValidateData(ctx, req.(*DataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataValidator_ServiceDesc is the grpc.ServiceDesc for DataValidator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataValidator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "drtest.DataValidator",
	HandlerType: (*DataValidatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateData",
			Handler:    _DataValidator_ValidateData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cmd/sidecar/src/proto/drtest.proto",
}
