FROM rust:latest AS builder
WORKDIR /usr/src/sidecar

RUN apt-get update && apt-get install -y protobuf-compiler && rm -rf /var/lib/apt/lists/*
COPY cmd/sidecar .
RUN cargo build --release

FROM gcr.io/distroless/cc-debian12
COPY --from=builder /usr/src/sidecar/target/release/sidecar /sidecar
CMD ["/sidecar"]