// Code generated by controller-gen. DO NOT EDIT.
package v1

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out.
func (in *ChaosDRTest) DeepCopyInto(out *ChaosDRTest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta) // Correctly copy ObjectMeta
	if in.Spec.AppSelector != nil {
		in, out := &in.Spec.AppSelector, &out.Spec.AppSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.Spec.ChaosType = in.Spec.ChaosType
	out.Spec.ValidationScript = in.Spec.ValidationScript
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, creating a new ChaosDRTest.
func (in *ChaosDRTest) DeepCopy() *ChaosDRTest {
	if in == nil {
		return nil
	}
	out := new(ChaosDRTest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out.
func (in *ChaosDRTestList) DeepCopyInto(out *ChaosDRTestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta) // Correctly copy ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ChaosDRTest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, creating a new ChaosDRTestList.
func (in *ChaosDRTestList) DeepCopy() *ChaosDRTestList {
	if in == nil {
		return nil
	}
	out := new(ChaosDRTestList)
	in.DeepCopyInto(out)
	return out
}
