[package]
name = "sidecar"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "0.12"
prost = "0.13"
tokio = { version = "1.40", features = ["rt-multi-thread", "macros"] }
minio-rsc = "0.2.6"
ring = "0.17"
hex = "0.4"

[build-dependencies]
tonic-build = "0.12"