apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: chaodrtests.chaosdr.io
spec:
  group: chaosdr.io
  names:
    kind: ChaosDRTest
    listKind: ChaosDRTestList
    plural: chaodrtests
    singular: chaodrtest
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              appSelector:
                type: object
                additionalProperties:
                  type: string
              chaosType:
                type: string
              validationScript:
                type: string
              validationConfig:
                type: object
                properties:
                  script:
                    type: string
                  apiEndpoint:
                    type: string
                  expectedStatusCode:
                    type: integer
                  databaseQuery:
                    type: object
                    properties:
                      connectionString:
                        type: string
                      query:
                        type: string
                      expectedRows:
                        type: integer
          status:
            type: object
            properties:
              success:
                type: boolean
              errorMessage:
                type: string
              backupName:
                type: string
              restoreName:
                type: string